### ISSUE TITLE
Missing fdrbench-0.0.1.jar

### ISSUE THREAD

**Issue by hollenstein** [Noble-Lab/FDRBench#1]
Dear developers,

I’ve read your preprint on bioRxiv with great interest. I found it very well prepared and easy to follow, and I fully agree that your findings have important implications for DIA analysis workflows.

I am working at a proteomics MS facility and we are using Spectronaut in our service for analyzing DIA data. As we are not using standard settings for filtering identifications, we would be interested in assessing how the actual false discovery rate behaves with different cut-offs in Spectronaut and for different data sets. Plus, we are considering lowering the protein q-value threshold by default to compensate for a potentially underestimated FDR.

The easiest way to do so would of course be to use your FDRBench tool. Since I couldn’t find the fdrbench-0.0.1.jar that is mentioned in the readme, I was wondering if it is released already and if not, if you have a release date in mind.

Best,
David Hollenstein

**Comment by wenbostar** [comment]
Hi David,

Thanks for your interest in our work. Please download the java tool at https://github.com/Noble-Lab/FDRBench/releases.

Bo

**Comment by hollenstein** [comment]
Thanks a lot!
