### ISSUE TITLE
Protein FDP calculation example in README not working in windows

### ISSUE THREAD

**Issue by hollenstein** [Noble-Lab/FDRBench#2]
Dear developers,

I've run into a minor issue with the example provided in the README for Protein FDP calculation, on a windows computer.
`java -jar fdrbench-0.0.1.jar -i protein-fdp_protein_input.tsv -level protein -o protein-diann_fdp_protein.csv -score 'score:0' -fold 1 -pick first`

Using double quotes for the score column fixed the issue for me. Using single quotes might not work in windows.
`-score "score:0"`

I also have a question regarding the score column. What is the meaning of the ":0"? I glanced over some of the code and I have a feeling it code be related to if a higher score is better? In any case, it would be helpful to document what this does in the parameters section.

Best,
David

**Comment by wenbostar** [comment]
Hi David, 

Thanks for pointing out this issue. I have improved the documentation for parameter "-score".

Bo
